import json
import time
from pathlib import Path

import pygame

DEFAULT_TEMPLATE_PATH = "mock/error_template.json"
COOLDOWN_SECONDS = 4.0


class AudioManager:
    """Plays pre-recorded coaching audio snippets, keyed by the error tags
    defined in error_template.json."""

    def __init__(self, template_path=DEFAULT_TEMPLATE_PATH, cooldown_seconds=COOLDOWN_SECONDS):
        self.project_root = Path(__file__).resolve().parent.parent
        self.template_path = self.project_root / template_path
        self.cooldown_seconds = cooldown_seconds

        pygame.mixer.init()

        self._errors = self._load_errors()
        self._sounds = {}
        self._last_played = {}

    def _load_errors(self):
        if not self.template_path.exists():
            raise FileNotFoundError(f"Error template not found: {self.template_path}")

        with open(self.template_path, "r", encoding="utf-8") as f:
            template = json.load(f)

        if "errors" not in template:
            raise ValueError(f"Error template missing 'errors' key: {self.template_path}")

        return {error["tag"]: error for error in template["errors"]}

    def _get_sound(self, tag):
        if tag not in self._sounds:
            audio_file = self._errors[tag]["audio_file"]
            audio_path = self.project_root / audio_file

            if not audio_path.exists():
                raise FileNotFoundError(f"Audio file not found for tag '{tag}': {audio_path}")

            self._sounds[tag] = pygame.mixer.Sound(str(audio_path))

        return self._sounds[tag]

    def play(self, tag):
        """Play the audio snippet for an error tag, unless it was just played
        within the cooldown window."""
        if tag not in self._errors:
            print(f"No audio mapping found for tag: {tag}")
            return False

        now = time.time()

        if now - self._last_played.get(tag, 0) < self.cooldown_seconds:
            return False

        try:
            self._get_sound(tag).play()
            self._last_played[tag] = now
            print(f"Playing audio for tag: {tag}")
            return True
        except (pygame.error, FileNotFoundError) as error:
            print(error)
            return False

    def play_sound(self, file_path):
        """Play an arbitrary .wav file, bypassing the error_template tag lookup
        and cooldown. This is the entry point for Team 3's slow layer: once
        Granite's text output has been converted to a .wav (via pyttsx3/gTTS),
        Team 3 calls this with the generated file's path."""
        audio_path = Path(file_path)
        if not audio_path.is_absolute():
            audio_path = self.project_root / audio_path

        if not audio_path.exists():
            print(f"Audio file not found: {audio_path}")
            return False

        try:
            pygame.mixer.Sound(str(audio_path)).play()
            print(f"Playing audio: {audio_path}")
            return True
        except pygame.error as error:
            print(error)
            return False

    def stop_all(self):
        pygame.mixer.stop()

    def shutdown(self):
        pygame.mixer.quit()


if __name__ == "__main__":
    audio_manager = AudioManager()

    # Fast layer: pre-recorded snippet keyed by error_template.json tag
    audio_manager.play("T1_late_braking")
    time.sleep(3)

    # Slow layer: ad-hoc .wav generated by Team 3 from Granite's text output
    audio_manager.play_sound("audio/granite_coaching_output.wav")
    time.sleep(3)

    audio_manager.shutdown()
