import sys
import json
import time
from pathlib import Path
import queue

GRANITE_DIR = Path(__file__).resolve().parent
SRC_DIR = GRANITE_DIR.parent
PROJECT_ROOT = SRC_DIR.parent

sys.path.insert(0, str(SRC_DIR))

_LATENCY_DIR = Path(__file__).resolve().parent.parent.parent / "tests" / "integration"
if str(_LATENCY_DIR) not in sys.path:
    sys.path.insert(0, str(_LATENCY_DIR))

from latency_logger import log_event
from llm.prompts import build_user_prompt
from llm.llm_client import ask_race_engineer
from llm.guardrail import apply_guardrail
from llm.coaching_style import get_system_prompt
from llm.rag import retrieve
from llm.llm_client import get_fallback_text

# If the LLM fails, skip retries and use fallback.
# After the cooldown, try the LLM again so temporary failures can recover.
_LLM_COOLDOWN_SECONDS = 10
_llm_retry_at = 0.0

def _llm_breaker_is_open():
    """True while the breaker is tripped: LLM calls should be skipped."""
    return time.time() < _llm_retry_at


def _trip_llm_breaker():
    global _llm_retry_at
    _llm_retry_at = time.time() + _LLM_COOLDOWN_SECONDS


def _reset_llm_breaker():
    global _llm_retry_at
    _llm_retry_at = 0.0

def process_single_error(error, system_prompt, audio_manager, force_fallback=False, feedback_callback=None, style="technical"):
    """Processes an isolated telemetry infraction."""
    error_type = error.get("type") or error.get("tag") or "generic_error"
    coaching_request = f"{error.get('message', '')} {error.get('coaching_hint', '')}".strip()
    # Use the same key across the coaching and audio logs so all events from the same request stay linked and END-TO-END latency can be calculated.
    latency_key = f"{error.get('session_id')}:{error.get('tag')}:{error.get('lap_number')}"

    # Fast Layer Event Interception
    if error.get("priority") == "high" or error_type in ["brake_now", "off_track"]:
        fast_text = error.get("message") or error.get("coaching_hint") or f"URGENT: {error_type.upper()}"

        if feedback_callback:
            feedback_callback(fast_text, layer="fast")

        # FastLayer already speaks these alerts immediately. Keep the event for dashboard, but don't play it again here.

        return None

    # Only enable the fallback script for slow-layer review when disconnected.
    if force_fallback or _llm_breaker_is_open():
        answer_text = get_fallback_text(error_type)
    else:
        # Execute RAG retrieval
        knowledge_chunks = retrieve(coaching_request, top_k=2)
        knowledge_context = "\n".join(knowledge_chunks)
        # Package context together for the LLM
        user_prompt = build_user_prompt(
            error.get("telemetry", {}),
            coaching_request,
            knowledge=knowledge_context
        )

        try:
            answer_text = ask_race_engineer(system_prompt, user_prompt)
            _reset_llm_breaker()
        except Exception:
            _trip_llm_breaker()
            answer_text = get_fallback_text(error_type)

    # Execute Slow Layer Feedback
    result = apply_guardrail(coaching_request, answer_text, error=error, style=style)
    log_event("guardrail_done", key=latency_key, detail=error_type)
    if result and result.get("is_valid", False):
        feedback_text = result.get("feedback", answer_text)
        print(f"\n[Slow Layer Feedback]: {feedback_text}")

        if feedback_callback:
            feedback_callback(feedback_text, layer="slow")

        # Playout to the driver in real time.
        audio_manager.play_text(
            feedback_text,
            priority="normal",
            cooldown_key=f"{error_type}_{error.get('corner')}",
            latency_key=latency_key,
        )
    return result

def _collect_sector_loss_lines(all_results):
    """Pull the "lost X s in Sector N" text already generated by
    detect_sector_time_loss out of the per-error coaching_context, so the lap
    summary can list each sector's loss without asking the LLM to invent it.
    Keeps the last (most up to date) note per sector, sorted S1/S2/S3.
    """
    notes = {}
    for r in all_results:
        if r.get("error_type") != "sector_time_loss":
            continue
        context = (r.get("coaching_context") or "").strip()
        if context:
            notes[r.get("corner", "Sector")] = context
    return [notes[corner] for corner in sorted(notes)]


def generate_summary(all_results, system_prompt, force_fallback=False):
    """Compiles all isolated coaching insights into a macro lap review summary."""
    if not all_results:
        return None, True

    if force_fallback or _llm_breaker_is_open():
        print("[AI Fast-Track Summary] Skipping LLM for Macro Summary due to empty quota.")
        return "Significant time lost in this sector. Focus on corner exits.", True

    lines = []
    for r in all_results:
        lines.append(
            f"- [{r.get('severity','?').upper()}] {r.get('error_type','?')} at {r.get('corner','?')}: {r.get('feedback','')}"
        )

    summary_prompt = f"""You are a professional race engineer giving a post-lap debrief.
    Below is all coaching feedback from this lap.

    {chr(10).join(lines)}

    Provide a concise summary (3-5 sentences) that:
    1. Identifies the single biggest area to improve
    2. Highlights recurring patterns across corners
    3. Gives one clear priority action for the next lap

    Be direct and actionable."""

    print("\n[AI] Compiling Macro Lap Summary Review")

    try:
        summary_text = ask_race_engineer(system_prompt, summary_prompt)
        _reset_llm_breaker()
        return summary_text, False
    except Exception as e:
        print(f"[AI Warning] Summary LLM failed: {e}")
        _trip_llm_breaker()
        return "Significant time lost in this sector. Focus on corner exits.", True


def ai_queue_consumer_loop(event_queue, audio_manager, stop_event, is_llm_available=True, feedback_callback=None, style="supportive"):
    """
    Asynchronously consumes error events from the queue. Receiving 'None' indicates
    that LiveCoach has finished the lap with no new events, which triggers the final summary.
    """
    if is_llm_available:
        _reset_llm_breaker()
    else:
        _trip_llm_breaker()

    system_prompt = get_system_prompt(style) # Coaching style (Supportive, aggressive, technical)
    all_results = []
    
    print("[AI Thread] Async Consumer active. Listening to shared_event_queue...")

    while not stop_event.is_set():
        try:
            event = event_queue.get(block=True, timeout=1.0)
            print(f">>> DEBUG got event: {event}")
            if event is not None:
                log_event("received", key=f"{event.get('session_id')}:{event.get('tag')}:{event.get('lap_number')}", detail=event.get("type"))
        except queue.Empty:
            continue

        if event is None:
            print("[AI Thread] Poison pill 'None' received. Race finished cleanly.")
            event_queue.task_done()
            break
            
        try:
            result = process_single_error(event, system_prompt, audio_manager, feedback_callback=feedback_callback, style=style)
            if result:
                merged = dict(result)
                merged["error_type"] = event.get("type", "generic_error")
                merged["corner"] = event.get("corner", "unknown")
                merged["severity"] = event.get("severity", "normal")
                all_results.append(merged)
        except Exception as e:
            print(f"[AI Thread Warning] Infraction processing failed: {e}")
        finally:
            event_queue.task_done()

    if audio_manager:
        if hasattr(audio_manager, "stop_all"):
            audio_manager.stop_all()
        elif hasattr(audio_manager, "clear"):
            audio_manager.clear()

    if stop_event.is_set():
        print("[AI Thread] Force stop signal detected. Aborting summary generation.")
        while not event_queue.empty():
            try:
                event_queue.get_nowait()
                event_queue.task_done()
            except queue.Empty:
                break
        return 

    if not all_results:
        print("[AI Thread] No infractions recorded. Exiting cleanly.")
        with open(PROJECT_ROOT / "data" / "lap_summary.json", "w", encoding="utf-8") as f:
            json.dump({"type": "lap_summary", "feedback": "Clean session with no major infractions recorded!"}, f, indent=2, ensure_ascii=False)
        return

    coaching_summary_path = PROJECT_ROOT / "data" / "coaching_summary.json"
    coaching_summary_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(coaching_summary_path, "w", encoding="utf-8") as f:
            json.dump({"total_errors": len(all_results), "coaching_results": all_results}, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"[AI Error] Failed to write coaching_summary: {e}")

    try:
        summary_text, _ = generate_summary(all_results, system_prompt)
        if summary_text:
            sector_lines = _collect_sector_loss_lines(all_results)
            if sector_lines:
                summary_text = summary_text.rstrip() + "\n\nSector Time Loss:\n" + "\n".join(f"- {line}" for line in sector_lines)

            summary_result = {
                "type": "lap_summary",
                "feedback": summary_text,
                "total_errors": len(all_results),
                "corners_affected": list({r.get("corner") for r in all_results})
            }

            with open(PROJECT_ROOT / "data" / "lap_summary.json", "w", encoding="utf-8") as f:
                json.dump(summary_result, f, indent=2, ensure_ascii=False)
            print("[AI SUCCESS] Summary successfully generated and saved to data/lap_summary.json.")
    except Exception as e:
        print(f"[AI Error] Macro debrief generation failed: {e}")